import type { Metadata } from "next";

import "../ui/theme/style-reset.css";
import "../ui/theme/base.css";
import { MainLayout } from "~/components/Layout";
import { PropsWithChildren } from "react";
import { AuthProvider } from "~/components/AuthProvider";
import { getSession } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const session = await getSession();

  return (
    <html lang="cs_CZ">
      <body>
        <AuthProvider session={session}>
          <MainLayout>{children}</MainLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
