import type { Metadata } from "next";

import "../ui/theme/style-reset.css";
import "../ui/theme/base.css";
import { MainLayout } from "~/components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs_CZ">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
